name: 🚀 Deploy Worker

'on':
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: europe-west1
  SERVICE_NAME: worker
  REPOSITORY: worker

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: 🏗️ Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔐 Check for secrets
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: 📥 Install dependencies
        run: npm install

      - name: 🧪 Run Tests
        run: npm test

      - name: 🔐 Google Auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/992838171690/locations/global/workloadIdentityPools/github-actions-pool/providers/worker'
          service_account: 'github-actions-sa@repo-490410.iam.gserviceaccount.com'
          export_environment_variables: true
          create_credentials_file: true

      - name: ⚙️ Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: 🐳 Docker Auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: 📤 Build and Push Container
        run: |
          DOCKER_TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:latest"
          docker build -t $DOCKER_TAG .
          docker push $DOCKER_TAG

      - name: 🚀 Deploy to Cloud Run
        id: deploy
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE_NAME }}
          region: ${{ env.REGION }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}:latest
          flags: '--allow-unauthenticated'

      - name: 🔥 Smoke test
        run: |
          URL=${{ steps.deploy.outputs.url }}
          echo "Testing: $URL"
          curl -f --retry 5 --retry-delay 3 "$URL"